# Generated by Django 5.0.7 on 2026-09-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_guest", models.BooleanField(db_column="isGuest", default=False)),
                (
                    "guest_email",
                    models.CharField(
                        blank=True, db_column="guestEmail", max_length=255, null=True
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True, db_column="guestName", max_length=255, null=True
                    ),
                ),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "salary_range",
                    models.JSONField(db_column="salaryRange", default=dict),
                ),
                ("questions", models.JSONField(default=list)),
                (
                    "current_question_index",
                    models.IntegerField(db_column="currentQuestionIndex", default=0),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "transcript_locked",
                    models.BooleanField(db_column="transcriptLocked", default=False),
                ),
                (
                    "final_report",
                    models.JSONField(db_column="finalReport", default=dict),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_column="expiresAt", null=True),
                ),
                ("media_urls", models.JSONField(db_column="mediaURLs", default=dict)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="userId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interview_sessions",
            },
        ),
    ]
