# Generated by Django 5.0.7 on 2026-09-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "provider_id",
                    models.CharField(
                        blank=True, db_column="providerId", max_length=255, null=True
                    ),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=50)),
                (
                    "valid_till",
                    models.DateTimeField(blank=True, db_column="validTill", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        db_column="institutionId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="institutions.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="userId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
    ]
