# Generated by Django 5.0.7 on 2026-09-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_level",
                    models.CharField(
                        db_column="roleLevel", default="support-admin", max_length=100
                    ),
                ),
                ("permissions", models.JSONField(default=list)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="createdBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_admins",
                        to="admin_panel.adminrecord",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admins",
            },
        ),
    ]
