# Generated by Django 5.0.7 on 2026-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "allowed_domains",
                    models.JSONField(db_column="allowedDomains", default=list),
                ),
                (
                    "per_student_price",
                    models.FloatField(db_column="perStudentPrice", default=0),
                ),
                (
                    "student_limit",
                    models.IntegerField(db_column="studentLimit", default=0),
                ),
                (
                    "students_registered",
                    models.IntegerField(db_column="studentsRegistered", default=0),
                ),
                (
                    "approval_status",
                    models.CharField(
                        db_column="approvalStatus", default="PENDING", max_length=50
                    ),
                ),
                (
                    "subscription_valid_till",
                    models.DateTimeField(
                        blank=True, db_column="subscriptionValidTill", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
            ],
            options={
                "db_table": "institutions",
            },
        ),
    ]
