# Generated by Django 5.0.7 on 2026-09-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(db_column="firstName", max_length=255)),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_column="lastName", default="", max_length=255
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "account_type",
                    models.CharField(
                        db_column="accountType", default="professional", max_length=50
                    ),
                ),
                (
                    "enrollment_number",
                    models.CharField(
                        blank=True,
                        db_column="enrollmentNumber",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "institution_email_verified",
                    models.BooleanField(
                        db_column="institutionEmailVerified", default=False
                    ),
                ),
                (
                    "interview_profile",
                    models.JSONField(db_column="interviewProfile", default=dict),
                ),
                (
                    "resume_url",
                    models.TextField(blank=True, db_column="resumeURL", null=True),
                ),
                ("resume_data", models.JSONField(db_column="resumeData", default=dict)),
                (
                    "used_guest_interview",
                    models.BooleanField(db_column="usedGuestInterview", default=False),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True, db_column="totpSecret", max_length=255, null=True
                    ),
                ),
                (
                    "totp_enabled",
                    models.BooleanField(db_column="totpEnabled", default=False),
                ),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("experience", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "desired_salary",
                    models.CharField(
                        blank=True, db_column="desiredSalary", max_length=255, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("skills", models.TextField(blank=True, null=True)),
                ("education", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="updatedAt"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        db_column="institutionId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
